---
name: dagger
on:
  push:
    branches: [main]

jobs:
  hello:
    name: Sync posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Call Dagger Function
        uses: dagger/dagger-for-github@v7
        env:
          DEVTO_TOKEN: ${{ secrets.DEVTO_TOKEN }}
        with:
          call: --dev-to-token env:DEVTO_TOKEN sync-posts
